### ISSUE TITLE
 [Errno 2] No such file or directory: './pts_in_hull.npy'

### ISSUE THREAD

**Issue by DiegoVallejoDev** [mauckc/colorize-video#2]
```bash
❯ python colorizeVideoV2.py -i '.\video\ color.mp4' -o colorized.mp4

Starting timing...

[INFO] warming up camera...
Traceback (most recent call last):
  File "colorizeVideoV2.py", line 78, in <module>
    pts_in_hull = np.load('./pts_in_hull.npy')
  File "C:\Python38\lib\site-packages\numpy\lib\npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './pts_in_hull.npy'
```

**Comment by KINGSAMP** [comment]
yoo, so you gotta go into ColorizedVideoV2.py and change replace the text on line 78 to this
pts_in_hull = np.load('models/pts_in_hull.npy')
